import AppKit
import Combine

/// Polls the general pasteboard for changes and keeps a short-lived, in-memory
/// history of captured items (newest first).
///
/// Pattern borrowed from Maccy (MIT): `NSPasteboard` has no change notification, so
/// we poll `changeCount` on a timer and snapshot when it moves. Sensitive items
/// (password managers, transient/auto-generated content) are skipped.
@MainActor
final class ClipboardManager: ObservableObject {

    // MARK: - Public surface

    /// Called on the main thread whenever `items` changes (ingest, copy, purge, clear).
    var onChange: (() -> Void)?

    /// Current history, newest first. `@Published` so SwiftUI/Combine observers (e.g. the
    /// history panel) re-render live on every mutation — a new copy, a screenshot ingest,
    /// a purge, or a clear. The `onChange` closure continues to fire as before.
    @Published private(set) var items: [ClipItem] = [] {
        didSet { onChange?() }
    }

    /// How long an item is kept before the purge timer removes it.
    var retention: TimeInterval

    // MARK: - Config

    private let maxItems: Int
    private let maxItemBytes: Int

    // MARK: - Polling state

    private var pollTimer: Timer?
    private var purgeTimer: Timer?
    private let pasteboard: NSPasteboard
    /// Last `changeCount` we have already processed (or that we produced ourselves).
    private var lastChangeCount: Int

    /// Pasteboard types that mark an item as sensitive/ephemeral — never stored.
    private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    // MARK: - Init

    /// - Parameters:
    ///   - retention: how long items live before the purge timer drops them (default 5 h).
    ///   - maxItems: hard cap on stored items (default 200).
    ///   - maxItemBytes: items larger than this are skipped (default 10 MB).
    init(retention: TimeInterval = 5 * 3600,
         maxItems: Int = 200,
         maxItemBytes: Int = 10 * 1024 * 1024,
         pasteboard: NSPasteboard = .general) {
        self.retention = retention
        self.maxItems = maxItems
        self.maxItemBytes = maxItemBytes
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Lifecycle

    /// Starts the poll and purge timers. Safe to call more than once.
    func start() {
        guard pollTimer == nil else { return }
        // Prime so anything already on the pasteboard at launch is not ingested.
        lastChangeCount = pasteboard.changeCount

        let poll = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.checkForChange() }
        }
        RunLoop.main.add(poll, forMode: .common)
        pollTimer = poll

        let purge = Timer(timeInterval: 60, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.purgeExpired() }
        }
        RunLoop.main.add(purge, forMode: .common)
        purgeTimer = purge
    }

    /// Stops both timers. History is retained in memory.
    func stop() {
        pollTimer?.invalidate()
        pollTimer = nil
        purgeTimer?.invalidate()
        purgeTimer = nil
    }

    // MARK: - Actions

    /// Re-copies an item to the pasteboard. Records the resulting `changeCount` so the
    /// next poll does not re-ingest our own write as a brand-new item.
    func copy(_ item: ClipItem) {
        item.write(to: pasteboard)
        lastChangeCount = pasteboard.changeCount

        // Move the copied item to the front (or insert if it was purged meanwhile).
        if let idx = items.firstIndex(where: { $0.id == item.id }) {
            items.remove(at: idx)
        }
        items.insert(ClipItem(id: item.id, date: Date(), kind: item.kind), at: 0)
        enforceCaps()
    }

    /// Pushes an image straight into history (used by the screenshot service). The
    /// image is NOT placed on the pasteboard here — the screenshot tool already does that.
    func ingestImage(_ image: NSImage) {
        guard let item = ClipItem.image(from: image) else { return }
        guard item.byteSize <= maxItemBytes else { return }
        items.insert(item, at: 0)
        enforceCaps()
    }

    /// Tell the manager the CURRENT pasteboard contents are already accounted for — e.g.
    /// we just wrote an image ourselves and ingested it via `ingestImage`. Without this,
    /// the next poll re-ingests the same content as a duplicate.
    func markCurrentPasteboardHandled() {
        lastChangeCount = pasteboard.changeCount
    }

    /// Removes all history.
    func clear() {
        guard !items.isEmpty else { return }
        items.removeAll()
    }

    /// Removes a single history item by id.
    func delete(id: ClipItem.ID) {
        items.removeAll { $0.id == id }
    }

    /// Drops items older than `retention`.
    func purgeExpired() {
        let cutoff = Date().addingTimeInterval(-retention)
        let kept = items.filter { $0.date >= cutoff }
        if kept.count != items.count {
            items = kept
        }
    }

    // MARK: - Polling

    private func checkForChange() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        ingestCurrentPasteboard()
    }

    private func ingestCurrentPasteboard() {
        // Sensitive / ephemeral content: never store.
        let presentTypes = Set(pasteboard.types ?? [])
        if !presentTypes.isDisjoint(with: ignoredTypes) { return }

        guard let item = snapshot() else { return }
        guard item.byteSize <= maxItemBytes else { return }

        items.insert(item, at: 0)
        enforceCaps()
    }

    /// Builds a `ClipItem` from the current pasteboard contents. Precedence:
    /// file URLs → image → text.
    private func snapshot() -> ClipItem? {
        // File URLs (real files on disk, not string-encoded).
        if let objects = pasteboard.readObjects(
                forClasses: [NSURL.self],
                options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !objects.isEmpty {
            return ClipItem(kind: .file(urls: objects))
        }

        let string = pasteboard.string(forType: .string)
        let hasString = !(string?.isEmpty ?? true)

        // RASTER image data (PNG/TIFF) → image. Screenshots and copied images carry this;
        // text does not. This is the reliable discriminator — even a screenshot that also
        // has an incidental string is still an image.
        if let data = pasteboard.data(forType: .png) ?? pasteboard.data(forType: .tiff),
           let image = NSImage(data: data),
           let png = ClipItem.pngData(from: image),
           let size = ClipItem.pixelSize(from: image) {
            return ClipItem(kind: .image(png: png, pixelSize: size))
        }

        // A real text string → TEXT. This is the fix for "text showing up in the Images
        // tab": copied text (incl. rich text/HTML) stays text even though NSImage(pasteboard:)
        // could conjure an image out of RTF/HTML/PDF content — we no longer let it.
        if let s = string, !s.isEmpty {
            return ClipItem(kind: .text(s))
        }

        // No text at all, but the pasteboard can still produce an image (e.g. a PDF or a
        // vendor image type with no raster data) → image, as a last resort.
        if !hasString,
           let image = NSImage(pasteboard: pasteboard),
           let png = ClipItem.pngData(from: image),
           let size = ClipItem.pixelSize(from: image) {
            return ClipItem(kind: .image(png: png, pixelSize: size))
        }

        return nil
    }

    // MARK: - Helpers

    private func enforceCaps() {
        if items.count > maxItems {
            items.removeLast(items.count - maxItems)
        }
    }

    // MARK: - Self-test (debug)

    /// Debug / self-test only: exercises ingest / delete / clear / dup-guard and returns a
    /// PASS/FAIL summary. Does NOT write to the pasteboard, so it won't clobber the clipboard.
    func debugSelfTest() -> String {
        func p(_ b: Bool) -> String { b ? "PASS" : "FAIL" }
        func testImage(_ i: Int) -> NSImage {
            let im = NSImage(size: NSSize(width: 20 + i, height: 20))
            im.lockFocus(); NSColor(white: CGFloat(i) / 4.0, alpha: 1).setFill()
            NSRect(x: 0, y: 0, width: 20 + i, height: 20).fill(); im.unlockFocus()
            return im
        }
        items.removeAll()
        (0..<3).forEach { ingestImage(testImage($0)) }
        let r1 = items.count == 3
        let midId = items[1].id
        delete(id: midId)
        let r2 = items.count == 2 && !items.contains { $0.id == midId }
        while let f = items.first { delete(id: f.id) }
        let r3 = items.isEmpty
        // Dup guard: ingest once, mark the pasteboard handled, poll → must NOT re-add.
        ingestImage(testImage(0))
        markCurrentPasteboardHandled()
        checkForChange()
        let r4 = items.count == 1
        // Delete it, poll again → must stay deleted (no phantom re-add — the "one remains" bug).
        delete(id: items[0].id)
        checkForChange()
        let r5 = items.isEmpty
        (0..<3).forEach { ingestImage(testImage($0)) }
        clear()
        let r6 = items.isEmpty
        items.removeAll()
        return "ingest3=\(p(r1)); deleteMiddle=\(p(r2)); deleteAll=\(p(r3)); "
             + "noDupAfterPoll=\(p(r4)); stayedDeleted=\(p(r5)); clearAll=\(p(r6))"
    }

    /// Debug / self-test only: verifies snapshot() classifies text as text and images as
    /// images (the "text showing in the Images tab" bug). Writes to THIS manager's
    /// pasteboard — construct it with a NON-general test pasteboard so it won't clobber
    /// the real clipboard.
    func debugClassifyTest() -> String {
        func p(_ b: Bool) -> String { b ? "PASS" : "FAIL" }
        func isText(_ i: ClipItem?) -> Bool { if case .text = i?.kind { return true }; return false }
        func isImage(_ i: ClipItem?) -> Bool { if case .image = i?.kind { return true }; return false }

        pasteboard.clearContents()
        pasteboard.setString("hello world", forType: .string)
        let plain = snapshot()

        pasteboard.clearContents()
        let img = NSImage(size: NSSize(width: 24, height: 24))
        img.lockFocus(); NSColor.red.setFill(); NSRect(x: 0, y: 0, width: 24, height: 24).fill(); img.unlockFocus()
        pasteboard.writeObjects([img])
        let image = snapshot()

        // Rich text (string + HTML, no raster) — the exact "text filed as image" case.
        pasteboard.clearContents()
        pasteboard.setString("styled text", forType: .string)
        pasteboard.setString("<b>styled</b>", forType: NSPasteboard.PasteboardType("public.html"))
        let rich = snapshot()

        pasteboard.clearContents()
        return "plainText→text=\(p(isText(plain))); image→image=\(p(isImage(image))); "
             + "richText→text=\(p(isText(rich)))"
    }
}
